### ISSUE TITLE
Will Coroutines 1.6 work with this library

### ISSUE THREAD

**Issue by asgarddesigns** [newrelic/newrelic-java-kotlin-coroutines#10]
## Summary

It looks like 1.6 support hasn't been mentioned, it may just mean a doco update but my initial integration doesn't seem to work, so I'm wondering if there's work that needs to be done. 

I thought it worth asking here if there's any issue while I troubleshoot!

**Comment by dhilpipre** [comment]
We basically check our instrumentation to verify that it still will load with current verision.  the Kotlin-Coroutines-1.4 will load and instrument the classes up to the current versions.
We do not however regularly test the instrumentation against current to make sure that the current versions work as expected,  We will test some of the sample apps against current versions to make sure that it works as expected.
Any details that you can share might help us to diagnose any potential problems

**Comment by dhilpipre** [comment]
The instrumentation has been tested against version 1.6 and 1.7 and our test apps are showing the data as expected.  We will close this issue unless specific problems can be identified.
