### ISSUE TITLE
Unexpected exception thrown in class transformer

### ISSUE THREAD

**Issue by Tapac** [newrelic/newrelic-java-kotlin-coroutines#8]
## Description
Sometime we've got a logged exception when new relic agent debug logging enabled in the production

## Steps to Reproduce
There is no clean way to reproduce it.

## Relevant Logs / Console output
```
com.newrelic FINE: Unexpected exception thrown in class transformer: 
jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68
--kotlinx/coroutines/CancellableContinuationImpl
java.lang.NullPointerException: null
```

## Your Environment
Kotlin 1.5.20
Kotlin-Coroutines: 1.5.0
Ktor 1.6.3
NewRelic Agent: 7.3.0
Newrelic Coroutines extension: 1.3/Kotlin-Coroutines_1.4

**Comment by dhilpipre** [comment]
cannot reproduce
